// Generated by Wrangler — matches wrangler.jsonc bindings exactly
// To regenerate: npm run cf-typegen
//
// WHY THIS FILE EXISTS:
//   TypeScript needs to know the shape of `env` at compile time.
//   Wrangler generates this from wrangler.jsonc so your Env interface
//   matches what Cloudflare actually injects at runtime.

interface Env {
	// D1 database — users, tasks, tags, task_tags
	DB: D1Database;

	// KV namespace — cache + rate limiting
	// Binding name MUST match wrangler.jsonc: "binding": "CACHE"
	CACHE: KVNamespace;

	// Workers AI — Llama-3 inference
	// Binding name MUST match wrangler.jsonc: "binding": "AI"
	AI: Ai;

	// Secret — set via: wrangler secret put JWT_SECRET
	JWT_SECRET: string;

	// Var — set in wrangler.jsonc "vars" block
	ENVIRONMENT: string;
}
